# Generated by Django 5.2.15 on 2026-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sos_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_user',
            },
        ),
    ]
