# Generated by Django 5.2.12 on 2026-03-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='ad',
        ),
    ]
