# Generated by Django 5.2.17 on 2026-09-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
