# Generated by Django 5.2.17 on 2026-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ors', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_user',
            },
        ),
    ]
