# Generated by Django 5.2.17 on 2026-09-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='addresss',
        ),
    ]
