# Generated by Django 5.2.17 on 2026-09-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0004_rename_address_user_addresss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addresss',
            new_name='address',
        ),
    ]
