# Generated by Django 5.2.12 on 2026-03-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('physics', models.FloatField(max_length=3)),
                ('chemistry', models.FloatField(max_length=3)),
                ('maths', models.FloatField(max_length=3)),
            ],
            options={
                'db_table': 'sos_marksheet',
            },
        ),
    ]
