# Generated by Django 5.2.15 on 2026-06-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='user_address',
        ),
    ]
