# Generated by Django 5.2.14 on 2026-06-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_rename_address_user_abcd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='abcd',
            new_name='address',
        ),
    ]
