# Generated by Django 5.0.6 on 2024-07-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
    ]
