# Generated by Django 5.1.7 on 2025-03-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first',
        ),
    ]
