# Generated by Django 5.1.7 on 2025-03-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_rename_firstname_user_first'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first',
            new_name='firstName',
        ),
    ]
